version: '3.8'

services:
  ann-diabetes-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
